/* als — writing an Ableton Live Set.

   A `.als` is gzipped XML, and the first version of this file wrote that XML from scratch. Live
   refused it ("Invalid Pointee Id"), and once the ids were right it crashed the loader outright.
   The lesson is in the crash: a Live Set is not a document you can infer from the outside. Live
   expects scenes, a clip slot per scene per track, take lanes, a transport and sixty-odd view
   states, and a set missing any of them is a set Live walks off the end of.

   So the shape comes from a set Live itself saved — src/als-template.js, generated by
   scripts/als-template.mjs — and this file only fills in what the song decides: the tempo, the
   meter, one track per part, and the notes. Everything structural is Live's own, verbatim.

   What it still cannot carry is the sound. Every instrument here is a Web Audio graph and there is
   no way to hand Live one, so the tracks arrive without devices — the same limit the MIDI export
   has, and the reason the stem bounce is the reference for how it should sound.

   Times are in beats throughout, which is what Live's XML uses. A bar is `beatsPerBar` of them. */

import { ALS_DOC, ALS_TRACK, ALS_CLIP } from "./als-template.js";

// XML text has to survive a section called "Verse & Chorus" or a sketch named after its author
const esc = s => String(s == null ? "" : s)
  .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;").replace(/'/g, "&apos;")
  // Live's parser stops at a control character, and a name can arrive with anything in it
  .replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g, "");
const alsNum = n => (Math.round(n * 1e6) / 1e6);

/* Live's palette, by index. These are the ones that read as a set on a timeline: the rhythm
   section warm, the harmony green, the melodic parts cool, and anything effects-like grey. */
const ALS_COLORS = { drums: 3, chords: 17, bass: 24, perc: 6, pad: 33, part: 12, fx: 8, other: 0 };

/* A time signature is one number in Live's XML: the denominator's place in 1, 2, 4, 8, 16, 32,
   times 99, plus the numerator less one. 4/4 is 2 × 99 + 3 = 201 — which is the value a scene in
   the reference set carries, so this is read off a real file rather than worked out. */
const TS_DENOMS = [1, 2, 4, 8, 16, 32];
const tsEnum = (num, den) => {
  const di = TS_DENOMS.indexOf(den);
  return (di < 0 ? 2 : di) * 99 + (Math.max(1, Math.min(99, Math.round(num))) - 1);
};

/* Ids. Live reads the whole document into one space and refuses a set — "Invalid Pointee Id" —
   where two objects claim one id, or one sits at or above NextPointeeId. The exception is the
   handful of ids that are numbered within their own list rather than the document, which is why
   Live's own tracks can all carry ClipSlot 0-7: those are the tags below, measured by comparing
   the tracks in a real set rather than assumed. Everything else in a cloned track is renumbered. */
const ALS_LOCAL_IDS = new Set(["ClipSlot", "AutomationLane", "TrackSendHolder", "TakeLane",
  "MidiClip", "KeyTrack", "RemoteableTimeSignature", "Scene", "SendPreBool", "Locator"]);
// `\s` before Id keeps this off NoteId and LomId, which are attributes rather than object ids
const ID_ATTR = /<([A-Za-z][\w.]*)((?:[^>"]|"[^"]*")*?\s)Id="(\d+)"/g;
const renumber = (xml, nextId) => xml.replace(ID_ATTR,
  (m, tag, pre) => ALS_LOCAL_IDS.has(tag) ? m : `<${tag}${pre}Id="${nextId()}"`);
const maxId = xml => {
  let max = 0;
  for (const m of xml.matchAll(ID_ATTR)) max = Math.max(max, Number(m[3]));
  return max;
};

/* One clip's worth of notes, grouped by pitch — Live stores a KeyTrack per note number rather than
   one flat list, so the grouping is the format's, not a choice. The note ids are the clip's own
   counter, and NoteIdGenerator below has to sit above the highest of them. */
const keyTracks = (notes) => {
  const byKey = new Map();
  for (const n of notes || []) {
    if (!byKey.has(n.note)) byKey.set(n.note, []);
    byKey.get(n.note).push(n);
  }
  let id = 1, key0 = 0;
  return [...byKey.entries()].sort((a, b) => a[0] - b[0]).map(([key, list]) => {
    const evs = list.sort((a, b) => a.t - b.t).map(n =>
      `<MidiNoteEvent Time="${alsNum(n.t)}" Duration="${alsNum(Math.max(0.005, n.dur))}" `
      + `Velocity="${Math.max(1, Math.min(127, Math.round(n.vel || 100)))}" OffVelocity="64" `
      + `NoteId="${id++}" />`).join("");
    return `<KeyTrack Id="${key0++}"><Notes>${evs}</Notes><MidiKey Value="${key}" /></KeyTrack>`;
  }).join("");
};

// one arrangement clip, starting at bar 1 and running the length of the song
const alsClip = ({ name, notes, end, color, tsNum, tsDen }) => ALS_CLIP
  .replace(/%START%/g, "0").replace(/%END%/g, alsNum(end)).replace(/%LENGTH%/g, alsNum(end))
  .replace(/%NAME%/g, esc(name)).replace(/%COLOR%/g, color)
  .replace(/%TSNUM%/g, tsNum).replace(/%TSDEN%/g, tsDen)
  .replace(/%NEXTNOTE%/g, (notes || []).length + 1)
  .replace(/%KEYTRACKS%/g, keyTracks(notes));

/* The set. `tracks` is [{ name, color, vol, notes:[{t,dur,note,vel}], end }] with every time in
   beats; `locators` is [{ beat, name }] — the section markers, which is what makes the arrangement
   legible on Live's ruler rather than an undifferentiated run of bars. */
function alsXml({ bpm, tsNum = 4, tsDen = 4, tracks = [], locators = [], name = "song" }) {
  const total = Math.max(4, ...tracks.map(t => t.end || 0));
  // clones start above every id the template shell already uses, and each one moves the mark along
  let next = maxId(ALS_DOC) + 1;
  const nextId = () => next++;
  const trackXml = tracks.map(t => renumber(ALS_TRACK
    .replace(/%CLIP%/g, () => alsClip({ name: t.name, notes: t.notes, end: t.end || total,
      color: t.color, tsNum, tsDen }))
    .replace(/%NAME%/g, esc(t.name)).replace(/%NOTE%/g, esc(t.note || ""))
    .replace(/%COLOR%/g, t.color).replace(/%VOL%/g, alsNum(t.vol == null ? 0.85 : t.vol)),
    nextId)).join("");
  const locXml = (locators || []).map((l, i) =>
    `<Locator Id="${i}"><LomId Value="0" /><Time Value="${alsNum(l.beat)}" />`
    + `<Name Value="${esc(l.name)}" /><Annotation Value="" />`
    + `<IsSongStart Value="${i === 0 ? "true" : "false"}" /></Locator>`).join("");
  return ALS_DOC
    .replace("%TRACKS%", () => trackXml)
    .replace("%LOCATORS%", () => locXml)
    .replace("%BPM%", alsNum(bpm))
    .replace("%TSID%", tsEnum(tsNum, tsDen))
    // clear of everything handed out above, and clear of the 1000 Live wants to see it above
    .replace("%NEXTID%", Math.max(21000, next + 1000));
}

/* Gzip, because that is what a .als is. `CompressionStream` is the same API the shared link uses,
   so there is no library here either — and if a browser is old enough to lack it, the caller is
   told rather than handed a file Live cannot open. */
async function alsBytes(spec) {
  const xml = alsXml(spec);
  const raw = new TextEncoder().encode(xml);
  const CS = globalThis.CompressionStream;
  if (!CS) return null;
  const stream = new Blob([raw]).stream().pipeThrough(new CS("gzip"));
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

export { ALS_COLORS, alsXml, alsBytes };
